export * from './ILocal';
export * from './ILogin';
export * from './IProducto';
export * from './IProveedor';
export * from './IUsuario';
export * from './IPlain-Stock';
export * from './IBaja-Stock';
export * from './IStock';
export * from './ITransferir-Stock';
